/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TeacherImport } from './routes/teacher'
import { Route as MyTasksImport } from './routes/myTasks'
import { Route as JanitorImport } from './routes/janitor'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TeacherRoute = TeacherImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRoute,
} as any)

const MyTasksRoute = MyTasksImport.update({
  id: '/myTasks',
  path: '/myTasks',
  getParentRoute: () => rootRoute,
} as any)

const JanitorRoute = JanitorImport.update({
  id: '/janitor',
  path: '/janitor',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/janitor': {
      id: '/janitor'
      path: '/janitor'
      fullPath: '/janitor'
      preLoaderRoute: typeof JanitorImport
      parentRoute: typeof rootRoute
    }
    '/myTasks': {
      id: '/myTasks'
      path: '/myTasks'
      fullPath: '/myTasks'
      preLoaderRoute: typeof MyTasksImport
      parentRoute: typeof rootRoute
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/janitor': typeof JanitorRoute
  '/myTasks': typeof MyTasksRoute
  '/teacher': typeof TeacherRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/janitor': typeof JanitorRoute
  '/myTasks': typeof MyTasksRoute
  '/teacher': typeof TeacherRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/janitor': typeof JanitorRoute
  '/myTasks': typeof MyTasksRoute
  '/teacher': typeof TeacherRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/janitor' | '/myTasks' | '/teacher'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/janitor' | '/myTasks' | '/teacher'
  id: '__root__' | '/' | '/janitor' | '/myTasks' | '/teacher'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JanitorRoute: typeof JanitorRoute
  MyTasksRoute: typeof MyTasksRoute
  TeacherRoute: typeof TeacherRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JanitorRoute: JanitorRoute,
  MyTasksRoute: MyTasksRoute,
  TeacherRoute: TeacherRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/janitor",
        "/myTasks",
        "/teacher"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/janitor": {
      "filePath": "janitor.tsx"
    },
    "/myTasks": {
      "filePath": "myTasks.tsx"
    },
    "/teacher": {
      "filePath": "teacher.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
